// <auto-generated />
using System;
using Engrana.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace api.Migrations
{
    [DbContext(typeof(EngranaContext))]
    [Migration("20250319055349_UpdatedAssetModel_CIModelCreated")]
    partial class UpdatedAssetModel_CIModelCreated
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ConfigurationItemConfigurationItem", b =>
                {
                    b.Property<Guid>("DownstreamConfigurationItemsId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UpstreamConfigurationItemsId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("DownstreamConfigurationItemsId", "UpstreamConfigurationItemsId");

                    b.HasIndex("UpstreamConfigurationItemsId");

                    b.ToTable("ConfigurationItemConfigurationItem");
                });

            modelBuilder.Entity("Engrana.Domain.Asset", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SerialNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Asset");
                });

            modelBuilder.Entity("Engrana.Domain.ConfigurationItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Location")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("Version")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ConfigurationItem");
                });

            modelBuilder.Entity("ConfigurationItemConfigurationItem", b =>
                {
                    b.HasOne("Engrana.Domain.ConfigurationItem", null)
                        .WithMany()
                        .HasForeignKey("DownstreamConfigurationItemsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Engrana.Domain.ConfigurationItem", null)
                        .WithMany()
                        .HasForeignKey("UpstreamConfigurationItemsId")
                        .OnDelete(DeleteBehavior.ClientCascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
